import { addMinutes, formatISO, set } from 'date-fns';
import type { PlannerInput } from '../domain/types';
import { v4 as uuid } from 'uuid';

const basePeople = [
  { id: 'pietro', name: 'Pietro Rossi', email: 'pietro@example.com' },
  { id: 'giulia', name: 'Giulia Neri', email: 'giulia@example.com' },
  { id: 'marco', name: 'Marco Bianchi', email: 'marco@example.com' },
];

function iso(date: Date) {
  return formatISO(date);
}

export function demoPlannerInput(date: string = formatISO(new Date())): PlannerInput {
  const today = new Date(date);
  const start = set(today, { hours: 7, minutes: 0, seconds: 0, milliseconds: 0 });

  return {
    date: formatISO(set(today, { hours: 0, minutes: 0, seconds: 0, milliseconds: 0 })),
    timezone: 'Europe/Rome',
    preferences: {
      workingHours: [
        { start: iso(set(today, { hours: 8 })), end: iso(set(today, { hours: 12, minutes: 30 })) },
        { start: iso(set(today, { hours: 14 })), end: iso(set(today, { hours: 18, minutes: 30 })) },
      ],
      focusBlocks: [
        { start: iso(set(today, { hours: 9 })), end: iso(set(today, { hours: 11 })) },
        { start: iso(set(today, { hours: 15 })), end: iso(set(today, { hours: 17 })) },
      ],
      meetingFreeDays: [5],
      timezone: 'Europe/Rome',
      minimumBreakMinutes: 15,
      transitionBufferMinutes: 10,
      defaultMeetingDurationMinutes: 30,
    },
    constraints: [
      {
        id: 'no-meetings-morning',
        type: 'SOFT',
        description: 'Preferisci mantenere le mattine per deep work',
        condition: 'meeting_before_11',
        priority: 4,
      },
      {
        id: 'lunch-break',
        type: 'HARD',
        description: 'Pausa pranzo obbligatoria',
        condition: '12:30-13:30',
        priority: 5,
      },
    ],
    tasks: [
      {
        id: 'task-1',
        title: 'Preparare roadmap Q2',
        estimatedMinutes: 120,
        dueDate: iso(addMinutes(start, 10 * 60)),
        priority: 'MUST',
        score: 95,
        tags: ['strategia'],
        project: 'OKR',
        dependencies: [],
        requiredPeople: [],
        preferredWindow: null,
        allowFragmentation: false,
        focusType: 'DEEP',
      },
      {
        id: 'task-2',
        title: 'Rispondere al thread clienti Nord',
        estimatedMinutes: 45,
        dueDate: iso(addMinutes(start, 8 * 60)),
        priority: 'SHOULD',
        score: 80,
        tags: ['email'],
        project: 'Supporto',
        dependencies: [],
        requiredPeople: [basePeople[1]!],
        preferredWindow: null,
        allowFragmentation: true,
        focusType: 'LIGHT',
      },
      {
        id: 'task-3',
        title: 'Sessione di mentoring con Luca',
        estimatedMinutes: 60,
        dueDate: iso(addMinutes(start, 9 * 60)),
        priority: 'MUST',
        score: 88,
        tags: ['people'],
        project: 'Coaching',
        dependencies: [],
        requiredPeople: [basePeople[0]!],
        preferredWindow: {
          start: iso(set(today, { hours: 16 })),
          end: iso(set(today, { hours: 18 })),
        },
        allowFragmentation: false,
        focusType: 'MEETING',
      },
      {
        id: 'task-4',
        title: 'Aggiornare Notion area prodotto',
        estimatedMinutes: 40,
        dueDate: null,
        priority: 'COULD',
        score: 50,
        tags: ['notion'],
        project: 'Product',
        dependencies: ['task-1'],
        requiredPeople: [],
        preferredWindow: null,
        allowFragmentation: true,
        focusType: 'LIGHT',
      },
      {
        id: 'task-5',
        title: 'Rivedere contratti partnership',
        estimatedMinutes: 90,
        dueDate: iso(addMinutes(start, 12 * 60)),
        priority: 'MUST',
        score: 92,
        tags: ['legale'],
        project: 'Partnership',
        dependencies: [],
        requiredPeople: [basePeople[2]!],
        preferredWindow: null,
        allowFragmentation: false,
        focusType: 'DEEP',
      },
      {
        id: 'task-6',
        title: 'Preparare email annuncio webinar',
        estimatedMinutes: 60,
        dueDate: iso(addMinutes(start, 14 * 60)),
        priority: 'SHOULD',
        score: 75,
        tags: ['marketing'],
        project: 'Webinar',
        dependencies: [],
        requiredPeople: [],
        preferredWindow: null,
        allowFragmentation: true,
        focusType: 'LIGHT',
      },
      {
        id: 'task-7',
        title: 'Analizzare metriche MRR',
        estimatedMinutes: 70,
        dueDate: iso(addMinutes(start, 11 * 60)),
        priority: 'MUST',
        score: 87,
        tags: ['analytics'],
        project: 'Finance',
        dependencies: [],
        requiredPeople: [],
        preferredWindow: {
          start: iso(set(today, { hours: 10 })),
          end: iso(set(today, { hours: 12 })),
        },
        allowFragmentation: false,
        focusType: 'DEEP',
      },
      {
        id: 'task-8',
        title: 'Call con fornitore infrastruttura',
        estimatedMinutes: 45,
        dueDate: iso(addMinutes(start, 13 * 60)),
        priority: 'SHOULD',
        score: 78,
        tags: ['meeting'],
        project: 'Ops',
        dependencies: [],
        requiredPeople: [basePeople[2]!],
        preferredWindow: {
          start: iso(set(today, { hours: 15 })),
          end: iso(set(today, { hours: 17 })),
        },
        allowFragmentation: false,
        focusType: 'MEETING',
      },
      {
        id: 'task-9',
        title: 'Allenamento in palestra',
        estimatedMinutes: 60,
        dueDate: iso(addMinutes(start, 16 * 60)),
        priority: 'SHOULD',
        score: 60,
        tags: ['personal'],
        project: null,
        dependencies: [],
        requiredPeople: [],
        preferredWindow: {
          start: iso(set(today, { hours: 19 })),
          end: iso(set(today, { hours: 21 })),
        },
        allowFragmentation: false,
        focusType: 'LIGHT',
      },
      {
        id: 'task-10',
        title: 'Preparare retrospettiva team',
        estimatedMinutes: 50,
        dueDate: iso(addMinutes(start, 9 * 60)),
        priority: 'MUST',
        score: 90,
        tags: ['team'],
        project: 'Ops',
        dependencies: [],
        requiredPeople: [],
        preferredWindow: null,
        allowFragmentation: false,
        focusType: 'DEEP',
      },
      {
        id: 'task-11',
        title: 'Revisionare PR critiche',
        estimatedMinutes: 45,
        dueDate: iso(addMinutes(start, 7 * 60)),
        priority: 'MUST',
        score: 85,
        tags: ['engineering'],
        project: 'Tech',
        dependencies: [],
        requiredPeople: [],
        preferredWindow: {
          start: iso(set(today, { hours: 8 })),
          end: iso(set(today, { hours: 10 })),
        },
        allowFragmentation: false,
        focusType: 'DEEP',
      },
      {
        id: 'task-12',
        title: 'Scrivere report aggiornamento investitori',
        estimatedMinutes: 90,
        dueDate: iso(addMinutes(start, 18 * 60)),
        priority: 'SHOULD',
        score: 82,
        tags: ['investor'],
        project: 'Finance',
        dependencies: [],
        requiredPeople: [],
        preferredWindow: null,
        allowFragmentation: true,
        focusType: 'DEEP',
      },
    ],
    events: [
      {
        id: 'event-1',
        title: 'Daily stand-up',
        start: iso(set(today, { hours: 9, minutes: 30 })),
        end: iso(set(today, { hours: 9, minutes: 45 })),
        source: 'EXTERNAL',
        meeting: {
          attendees: basePeople,
          meetingLink: 'https://meet.google.com/xyz',
        },
        category: 'MEETING',
        flexibility: 'FIXED',
        createdFrom: 'CALENDAR',
      },
      {
        id: 'event-2',
        title: 'Allineamento reparto prodotto',
        start: iso(set(today, { hours: 11, minutes: 30 })),
        end: iso(set(today, { hours: 12, minutes: 15 })),
        source: 'EXTERNAL',
        meeting: {
          attendees: basePeople,
          meetingLink: 'https://teams.microsoft.com/l/meetup-join/example',
        },
        category: 'MEETING',
        flexibility: 'FIXED',
        createdFrom: 'CALENDAR',
      },
      {
        id: 'event-3',
        title: 'Pranzo rigenerante',
        start: iso(set(today, { hours: 13 })),
        end: iso(set(today, { hours: 14 })),
        source: 'INTERNAL',
        meeting: {
          attendees: [],
          meetingLink: null,
        },
        category: 'PERSONAL',
        flexibility: 'MOVABLE',
        createdFrom: 'SYSTEM',
      },
    ],
    emailActions: [
      {
        id: 'email-1',
        subject: 'Richiesta aggiornamento progetto Phoenix',
        snippet: 'Ciao, puoi inviarci entro domani uno stato del progetto?',
        extractedTasks: [
          {
            id: uuid(),
            title: 'Preparare stato progetto Phoenix',
            estimatedMinutes: 30,
            dueDate: iso(addMinutes(start, 20 * 60)),
            priority: 'SHOULD',
            score: 70,
            tags: ['email'],
            project: 'Phoenix',
            dependencies: [],
            requiredPeople: [],
            preferredWindow: null,
            allowFragmentation: true,
            focusType: 'LIGHT',
          },
        ],
        dueDate: iso(addMinutes(start, 20 * 60)),
        participants: [basePeople[1]!],
      },
    ],
  };
}
